version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vms_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - vms-network

    db:
        image: mysql:8.0
        container_name: vms_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_USER: ${DB_USERNAME:-laravel}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - vms-network

    nginx:
        image: nginx:1.21
        container_name: vms_nginx
        restart: unless-stopped
        ports:
            - "8006:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - vms-network

networks:
    vms-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
