version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vms_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - appdata:/var/www
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-laravel}
            - DB_USERNAME=${DB_USERNAME:-laravel}
            - DB_PASSWORD=${DB_PASSWORD:-secret}
        networks:
            - vms-network
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: vms_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_USER: ${DB_USERNAME:-laravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_secret}
        volumes:
            - vmsdbdata:/var/lib/mysql
        networks:
            - vms-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 5
            start_period: 20s

    nginx:
        image: nginx:1.21
        container_name: vms_nginx
        restart: unless-stopped
        ports:
            - "8006:80"
        volumes:
            - appdata:/var/www
            # - ./docker/nginx/conf.d:/etc/nginx/conf.d:delegated
        networks:
            - vms-network
        depends_on:
            - app
        entrypoint:
            [
                "/bin/sh",
                "-c",
                "cp -r /var/www/docker/nginx/conf.d/* /etc/nginx/conf.d/ && nginx -g 'daemon off;'",
            ]

networks:
    vms-network:
        driver: bridge

volumes:
    vmsdbdata:
        driver: local
    appdata:
        driver: local
