version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vms_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-laravel}
            - DB_USERNAME=${DB_USERNAME:-laravel}
            - DB_PASSWORD=${DB_PASSWORD:-secret}
        networks:
            - vms-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: vms_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_USER: ${DB_USERNAME:-laravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_secret}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - vms-network
        ports:
            - "3309:3306"

    nginx:
        image: nginx:1.21
        container_name: vms_nginx
        restart: unless-stopped
        ports:
            - "8006:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - vms-network
        depends_on:
            - app

networks:
    vms-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
