version: "3.8"

services:
    app:
        build: .
        ports:
            - "8005:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_KEY=${DB_CONNECTION}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - vms-network

    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        healthcheck:
            test:
                ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD"]
            interval: 5s
            timeout: 3s
            retries: 10
        networks:
            - vms-network

networks:
    vms-network:
        driver: bridge

volumes:
    db_data:
