version: "3.8"

services:
    app:
        build: .
        ports:
            - "8005:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV:-local}
            - APP_KEY=${DB_CONNECTION:-Wh2nCH1TmG/pPbQYWgZ/eYjkH+VTirnySwYspdap80Q=}
            - DB_CONNECTION=${DB_CONNECTION:-MySQL}
            - DB_HOST=${DB_HOST:-db}
            - DB_PORT=${DB_PORT:-3306}
            - DB_DATABASE=${DB_DATABASE:-laravel}
            - DB_USERNAME=${DB_USERNAME:-vms_user}
            - DB_PASSWORD=${DB_PASSWORD:-vms_pass}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - vms-network

    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-vms_root_pass}
            - MYSQL_DATABASE=${DB_DATABASE:-laravel}
            - MYSQL_USER=${DB_USERNAME:-vms_user}
            - MYSQL_PASSWORD=${DB_PASSWORD:-vms_pass}
        healthcheck:
            test:
                ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD"]
            interval: 5s
            timeout: 3s
            retries: 10
        networks:
            - vms-network

networks:
    vms-network:
        driver: bridge

volumes:
    db_data:
